# Generated by Django 5.0.6 on 2026-03-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_category_alter_task_options_task_due_date_task_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#6366f1', max_length=20),
        ),
    ]
